version: '3.6'


services:
  jupyter:
    image: rajasoun/ds:0.1
    container_name: data_science_py
    ports:
     - "8888:8888"
    volumes:
      - jupyter_notebooks:/opt      


volumes:
  jupyter_notebooks:
    driver_opts:
      type: none
      device: $PWD/notebooks
      o: bind